name: flowrec
channels:
- conda-forge
- pkgs/main
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- aiohttp=3.8.4
- aiosignal=1.3.1
- alsa-lib=1.2.8
- aom=3.5.0
- asttokens=2.0.5
- async-timeout=4.0.2
- attr=2.5.1
- attrs=22.1.0
- backcall=0.2.0
- blosc=1.21.3
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2023.01.10
- cached-property=1.5.2
- cached_property=1.5.2
- cairo=1.16.0
- certifi=2022.12.7
- cffi=1.15.1
- cftime=1.6.2
- charset-normalizer=2.0.4
- colorama=0.4.6
- contourpy=1.0.7
- coolprop=6.4.1
- cryptography=39.0.1
- curl=8.0.1
- cycler=0.11.0
- dbus=1.13.6
- debugpy=1.5.1
- decorator=5.1.1
- double-conversion=3.2.0
- eigen=3.4.0
- executing=0.8.3
- expat=2.5.0
- ffmpeg=5.1.2
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.39.3
- freetype=2.12.1
- frozenlist=1.3.3
- gettext=0.21.1
- gl2ps=1.4.2
- glew=2.1.0
- glib=2.76.1
- glib-tools=2.76.1
- gmp=6.2.1
- gnutls=3.7.8
- graphite2=1.3.13
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- h5py=3.8.0
- harfbuzz=6.0.0
- hdf4=4.2.15
- hdf5=1.14.0
- icu=72.1
- idna=3.4
- imageio=2.27.0
- importlib-metadata=6.5.0
- importlib_metadata=6.5.0
- ipykernel=6.15.0
- ipython=8.10.0
- jedi=0.18.1
- jsoncpp=1.9.5
- jsonschema=4.17.3
- jupyter_client=8.1.0
- jupyter_core=5.3.0
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.20.1
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.38
- lerc=4.0.0
- libaec=1.0.6
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.67
- libcblas=3.9.0
- libclang=16.0.1
- libclang13=16.0.1
- libcups=2.3.3
- libcurl=8.0.1
- libdeflate=1.18
- libdrm=2.4.114
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.2
- libgcc-ng=12.2.0
- libgcrypt=1.10.1
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libglib=2.76.1
- libglu=9.0.0
- libgomp=12.2.0
- libgpg-error=1.46
- libhwloc=2.9.1
- libiconv=1.17
- libidn2=2.3.4
- libjpeg-turbo=2.1.5.1
- liblapack=3.9.0
- libllvm16=16.0.1
- libnetcdf=4.9.2
- libnghttp2=1.52.0
- libnsl=2.0.0
- libogg=1.3.4
- libopenblas=0.3.21
- libopus=1.3.1
- libpciaccess=0.17
- libpng=1.6.39
- libpq=15.2
- libsndfile=1.2.0
- libsodium=1.0.18
- libsqlite=3.40.0
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libsystemd0=253
- libtasn1=4.19.0
- libtheora=1.1.1
- libtiff=4.5.0
- libunistring=0.9.10
- libuuid=2.38.1
- libva=2.18.0
- libvorbis=1.3.7
- libvpx=1.11.0
- libwebp-base=1.3.0
- libxcb=1.13
- libxkbcommon=1.5.0
- libxml2=2.10.4
- libzip=1.9.2
- libzlib=1.2.13
- loguru=0.7.0
- lz4-c=1.9.4
- markdown-it-py=2.2.0
- matplotlib-base=3.7.1
- matplotlib-inline=0.1.6
- mdurl=0.1.0
- meshio=5.3.4
- mpg123=1.31.3
- multidict=6.0.4
- munkres=1.1.4
- mysql-common=8.0.32
- mysql-libs=8.0.32
- nbformat=5.7.0
- ncurses=6.4
- nest-asyncio=1.5.6
- netcdf4=1.6.3
- nettle=3.8.1
- nlohmann_json=3.11.2
- nspr=4.35
- nss=3.89
- numpy=1.24.2
- openh264=2.3.1
- openjpeg=2.5.0
- openssl=3.1.0
- p11-kit=0.24.1
- packaging=23.0
- pandas=2.0.0
- parso=0.8.3
- pcre2=10.40
- pexpect=4.8.0
- pickleshare=0.7.5
- pigar=0.10.0
- pillow=9.5.0
- pip=23.1
- pixman=0.40.0
- platformdirs=2.5.2
- pooch=1.7.0
- proj=9.1.1
- prompt-toolkit=3.0.36
- psutil=5.9.0
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pugixml=1.11.4
- pulseaudio-client=16.1
- pure_eval=0.2.2
- pycparser=2.21
- pygments=2.11.2
- pyopenssl=23.0.0
- pyparsing=3.0.9
- pyrsistent=0.18.0
- pysocks=1.7.1
- python=3.11.3
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.2
- python-tzdata=2023.3
- python_abi=3.11
- pytz=2023.3
- pyvista=0.38.5
- pyzmq=23.2.0
- qt-main=5.15.8
- readline=8.2
- requests=2.28.1
- rich=13.3.1
- scipy=1.10.1
- scooby=0.7.1
- setuptools=65.6.3
- six=1.16.0
- snappy=1.1.10
- sqlite=3.41.1
- stack_data=0.2.0
- svt-av1=1.4.1
- tbb=2021.9.0
- tbb-devel=2021.9.0
- tk=8.6.12
- tornado=6.2
- traitlets=5.7.1
- typing-extensions=4.5.0
- typing_extensions=4.5.0
- tzdata=2023c
- urllib3=1.26.15
- utfcpp=3.2.3
- vtk=9.2.6
- vtk-base=9.2.6
- vtk-io-ffmpeg=9.2.6
- wcwidth=0.2.5
- wheel=0.38.4
- wslink=1.10.1
- x264=1!164.3095
- x265=3.5
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xkeyboard-config=2.38
- xorg-fixesproto=5.0
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.8.4
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxfixes=5.0.3
- xorg-libxrender=0.9.10
- xorg-libxt=1.2.1
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xf86vidmodeproto=2.3.1
- xorg-xproto=7.0.31
- xz=5.2.10
- yarl=1.8.2
- zeromq=4.3.4
- zipp=3.15.0
- zlib=1.2.13
- zstd=1.5.2

