name: frenv
channels:
- conda-forge
- pkgs/main
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- asttokens=2.0.5
- attrs=22.1.0
- backcall=0.2.0
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2023.01.10
- cached-property=1.5.2
- cached_property=1.5.2
- certifi=2022.12.7
- cffi=1.15.1
- charset-normalizer=2.0.4
- colorama=0.4.6
- cryptography=39.0.1
- debugpy=1.5.1
- decorator=5.1.1
- executing=0.8.3
- h5py=3.8.0
- hdf5=1.14.0
- idna=3.4
- ipykernel=6.15.0
- ipython=8.10.0
- jedi=0.18.1
- jsonschema=4.17.3
- jupyter_client=8.1.0
- jupyter_core=5.3.0
- keyutils=1.6.1
- krb5=1.20.1
- ld_impl_linux-64=2.38
- libaec=1.0.6
- libblas=3.9.0
- libcblas=3.9.0
- libcurl=7.87.0
- libedit=3.1.20191231
- libev=4.33
- libffi=3.4.2
- libgcc-ng=12.2.0
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libgomp=12.2.0
- liblapack=3.9.0
- libnghttp2=1.51.0
- libopenblas=0.3.21
- libsodium=1.0.18
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libuuid=1.41.5
- libzlib=1.2.13
- matplotlib-inline=0.1.6
- nbformat=5.7.0
- ncurses=6.4
- nest-asyncio=1.5.6
- numpy=1.24.2
- openssl=1.1.1t
- packaging=23.0
- parso=0.8.3
- pexpect=4.8.0
- pickleshare=0.7.5
- pigar=0.10.0
- pip=23.0.1
- platformdirs=2.5.2
- prompt-toolkit=3.0.36
- psutil=5.9.0
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pycparser=2.21
- pygments=2.11.2
- pyopenssl=23.0.0
- pyrsistent=0.18.0
- pysocks=1.7.1
- python=3.11.2
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.2
- python_abi=3.11
- pyzmq=23.2.0
- readline=8.2
- requests=2.28.1
- setuptools=65.6.3
- six=1.16.0
- sqlite=3.41.1
- stack_data=0.2.0
- tk=8.6.12
- tornado=6.2
- traitlets=5.7.1
- tzdata=2023c
- urllib3=1.26.15
- wcwidth=0.2.5
- wheel=0.38.4
- xz=5.2.10
- zeromq=4.3.4
- zlib=1.2.13

